<?php
// Enable error reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Set headers for CSV download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=dive_logs_template.csv');

// Create output stream
$output = fopen('php://output', 'w');

// Write CSV header
fputcsv($output, [
    'ID (leave empty)',
    'Location (REQUIRED)',
    'Dive Site',
    'Latitude (REQUIRED if no location)',
    'Longitude (REQUIRED if no location)',
    'Date (REQUIRED, YYYY-MM-DD)',
    'Time',
    'Description',
    'Depth (m)',
    'Duration (min)',
    'Water Temperature (°C)',
    'Air Temperature (°C)',
    'Visibility (m)',
    'Buddy',
    'Dive Site Type',
    'Activity Type',
    'Rating (1-5)',
    'Comments',
    'Fish Sightings (ignored for import)'
], ',', '"', '\\');

// Write one example row with empty values
fputcsv($output, [
    '', // Leave ID empty - will be automatically generated by database
    'Great Barrier Reef', // Required location
    'Ribbon Reef #5', // Optional specific dive site name
    '16.2181', // Latitude - can be left empty if location provided
    '145.4730', // Longitude - can be left empty if location provided
    '2023-01-15', // Required date in YYYY-MM-DD format
    '14:30', // Optional time
    'Beautiful coral formations with diverse marine life', // Optional description
    '18.5', // Optional depth in meters
    '45', // Optional duration in minutes
    '24.5', // Optional water temperature in °C
    '28.2', // Optional air temperature in °C
    '15', // Optional visibility in meters
    'John Doe', // Optional buddy/dive partner
    'Reef', // Optional dive site type
    'diving', // Optional activity type (diving or snorkeling)
    '4', // Optional rating (1-5)
    'Spotted several turtles and a reef shark', // Optional comments
    '' // Fish sightings (not used for import)
], ',', '"', '\\');

// Write a second example with only mandatory fields
fputcsv($output, [
    '', // Leave ID empty
    'Maldives Reef', // Only location (will be geocoded)
    '', // No dive site
    '', // No latitude (will be geocoded from location)
    '', // No longitude (will be geocoded from location)
    '2023-02-20', // Required date
    '', '', '', '', '', '', '', '', '', '', '', '' // All other fields empty
], ',', '"', '\\');

// Close file pointer
fclose($output);
?> 